version: '3.8'

services:
  # --------------- 基础服务 ---------------
  postgres:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:RELEASE.2023-08-16T20-17-30Z
    command: server /data --console-address ":9001"
    env_file: .env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # --------------- 应用服务 ---------------
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1

  # --------------- Celery Worker ---------------
  celery:
    build:
      context: .
      dockerfile: docker/celery.Dockerfile
    env_file: .env
    depends_on:
      - redis
    environment:
      - CELERY_WORKER_NAME=worker@%n
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

volumes:
  postgres_data:
  redis_data:
  minio_data: